project:
  type: website

website:
  title: "CaviR"
  #margin-header: subscribe.html
  search:
    location: navbar
    type: textbox
  page-footer: 
    center: "Copyright 2023, Joachim Waterschoot"
    background: light
  navbar:
    logo: "logo.png"
    style: "docked"
    pinned: true
    right:
      - href: Package.qmd
        text: The package
      - href: DataRt.qmd
        text: Code in R
      - about.qmd
    tools:
    # - icon: twitter
    #   href: https://twitter.com
    - icon: github
      menu:
        - text: Report a Bug
          url:  https://bugs.com

format:
  html:
    theme: flatly #flatly #simplex
    css: styles.css
    toc: true

editor: visual

